export const personalData = {
  name: 'Varshan K',
  title: 'Full-Stack Developer • Python • SQL • Data Engineering',
  tagline: 'Engineering scalable MERN & PERN applications, ETL pipelines, and data architectures',
  description: 'B.Com Information Technology graduate with hands-on expertise in full-stack web development, Python, and relational/NoSQL database systems. Proficient in engineering scalable applications across the MERN and PERN stacks, alongside crafting data-focused architectures with Pandas, NumPy, and SQL. Proactive collaborator with strong experience across academic projects and hackathons. Eager to leverage strong problem-solving capabilities in an entry-level Full-Stack Developer, Software Developer, or Data Engineer role.',
  location: 'Coimbatore, Tamil Nadu – 641668',
  email: 'varshanrio05@gmail.com',
  phone: '+91 9626949995',
  linkedin: 'https://linkedin.com/in/varshan-k-v005',
  github: 'https://github.com/varshan054685',
  instagram: 'https://instagram.com/im_luffy_56',
  whatsapp: 'https://wa.me/919626949995',
  resumeLink: '/Varshan_Resume.pdf',
  portfolioLink: 'https://varshan-portfolio.vercel.app',
};

export const areasOfFocus = [
  'Full-Stack Development',
  'Data Engineering',
  'ETL Pipelines',
  'SQL & Relational DBs',
  'AI Integration',
  'Responsive UI/UX',
];

export const skills = {
  categories: [
    {
      title: 'Languages',
      skills: [
        { name: 'Python', icon: '/icons/skills/python.svg', color: '#3776ab', description: 'Primary language for backend logic, ETL pipelines, and data manipulation.' },
        { name: 'JavaScript (ES6+)', icon: '/icons/skills/javascript.svg', color: '#f7df1e', description: 'Core language for interactive web applications and full-stack development.' },
        { name: 'TypeScript', icon: '/icons/skills/typescript.svg', color: '#3178c6', description: 'Strongly typed JavaScript for robust, scalable web applications.' },
        { name: 'HTML5', icon: '/icons/skills/html5.svg', color: '#e34c26', description: 'Structuring web content with clean, accessible markup.' },
        { name: 'CSS3', icon: '/icons/skills/css3.svg', color: '#264de4', description: 'Modern styling, responsive layouts, and animations.' },
      ],
    },
    {
      title: 'Frontend & UI',
      skills: [
        { name: 'React.js', icon: '/icons/skills/react.svg', color: '#61dafb', description: 'Building interactive dashboards, SPAs, and stateful React components.' },
        { name: 'Next.js', icon: '/icons/skills/nextjs.svg', color: '#ffffff', description: 'Full-stack React framework for optimized server rendering and static site generation.' },
        { name: 'Tailwind CSS', icon: '/icons/skills/tailwindcss.svg', color: '#06b6d4', description: 'Utility-first styling for rapid, highly responsive UI development.' },
        { name: 'Material UI', icon: '/icons/skills/materialui.svg', color: '#007fff', description: 'Professional UI component library for React applications.' },
      ],
    },
    {
      title: 'Backend & APIs',
      skills: [
        { name: 'Node.js', icon: '/icons/skills/nodejs.svg', color: '#339933', description: 'Asynchronous event-driven runtime for backend services.' },
        { name: 'Express.js', icon: '/icons/skills/express.svg', color: '#ffffff', description: 'Building scalable RESTful API endpoints and web servers.' },
        { name: 'Flask', icon: '/icons/skills/flask.svg', color: '#ffffff', description: 'Python micro-framework for serving AI models and REST backend services.' },
        { name: 'RESTful APIs', icon: '/icons/skills/rest-api.svg', color: '#bc13fe', description: 'Designing stateful & stateless APIs connected with frontend applications.' },
      ],
    },
    {
      title: 'Databases',
      skills: [
        { name: 'SQL', icon: '/icons/skills/sql.svg', color: '#e48e00', description: 'Formulating optimized analytical queries and relational database schemas.' },
        { name: 'PostgreSQL', icon: '/icons/skills/postgresql.svg', color: '#336791', description: 'Architecting relational schemas, multi-dimensional tables, and complex SQL analytics.' },
        { name: 'MongoDB', icon: '/icons/skills/mongodb.svg', color: '#47a248', description: 'Flexible NoSQL document storage for MERN stack applications.' },
      ],
    },
    {
      title: 'Data & Analytics',
      skills: [
        { name: 'Pandas', icon: '/icons/skills/Pandas.svg', color: '#150458', description: 'Data extraction, transformation, anomaly filtering, and vectorized processing.' },
        { name: 'NumPy', icon: '/icons/skills/numpy.svg', color: '#013243', description: 'High-performance numerical computing and array data operations.' },
        { name: 'Matplotlib', icon: '/icons/skills/Matplotlib.svg', color: '#11557c', description: 'Crafting analytical plots and data visual charts in Python.' },
        { name: 'Seaborn', icon: '/icons/skills/Seaborn.svg', color: '#3776ab', description: 'Statistical data visualization built on top of Matplotlib.' },
        { name: 'Power BI', icon: '/icons/skills/power-bi.svg', color: '#f2c811', description: 'Building interactive business intelligence dashboards and reporting.' },
        { name: 'Tableau', icon: '/icons/skills/tableau.svg', color: '#e97627', description: 'Visual analytical reports and data presentation.' },
      ],
    },
    {
      title: 'Tools & Workflow',
      skills: [
        { name: 'Git', icon: '/icons/skills/git.svg', color: '#f05032', description: 'Distributed version control and branch management.' },
        { name: 'GitHub', icon: '/icons/skills/github.svg', color: '#ffffff', description: 'Code hosting, collaboration, and project management.' },
        { name: 'VS Code', icon: '/icons/skills/vs-code.svg', color: '#007acc', description: 'Primary IDE for full-stack and data engineering development.' },
        { name: 'Antigravity', icon: '/icons/skills/antigravity.svg', color: '#bc13fe', description: 'Agentic AI development platform and intelligent development workflows.' },
      ],
    },
  ],
  workApproach: [
    {
      title: 'Collaboration',
      description: 'Proactive collaborator in fast-paced hackathons and team projects, focusing on code reviews and shared project goals.',
      icon: 'Users',
    },
    {
      title: 'Coding Principles',
      description: 'Committed to clean architecture, DRY principles, schema validation, and scalable system design.',
      icon: 'Code2',
    },
    {
      title: 'Problem-Solving',
      description: 'Approaching complex data and web challenges with systematic debugging and architectural thinking.',
      icon: 'Lightbulb',
    },
    {
      title: 'Continuous Learning',
      description: 'Constantly expanding full-stack capabilities, data engineering workflows, and AI integrations.',
      icon: 'TrendingUp',
    },
  ],
  currentlyLearning: [
    { name: 'Advanced Data Engineering & Cloud ETL', icon: 'Server' },
    { name: 'System Design & Relational Optimization', icon: 'Layout' },
    { name: 'AI Backend & LLM Integration Patterns', icon: 'Atom' },
  ],
};

export const projects = [
  {
    id: 1,
    title: 'Sales Data ETL Pipeline',
    description: 'Automated ETL pipeline extracting raw sales records, transforming anomalies, and staging clean datasets.',
    longDescription: 'Designed and implemented an automated ETL pipeline extracting raw sales records, transforming data anomalies, and staging clean datasets. Leveraged Pandas and NumPy for vectorised processing, structuring schema-validated tables for analytical queries and dashboards.',
    image: '/images/sales-etl.jpg',
    tech: ['Python', 'Pandas', 'NumPy', 'PostgreSQL', 'ETL Pipelines'],
    github: 'https://github.com/varshan054685',
    live: null,
    featured: true,
  },
  {
    id: 2,
    title: 'E-Commerce Data Warehouse',
    description: 'Relational database schemas organizing multi-dimensional customer, product, transaction, and order records.',
    longDescription: 'Architected relational database schemas organizing multi-dimensional customer, product, transaction, and order records. Formulated optimized SQL analytical queries and built data ingestion scripts in Python for seamless analytics.',
    image: '/images/data-warehouse.jpg',
    tech: ['Python', 'SQL', 'PostgreSQL', 'Data Warehousing'],
    github: 'https://github.com/varshan054685',
    live: null,
    featured: true,
  },
  {
    id: 3,
    title: 'DataMind AI',
    description: 'AI-powered Data Science Operating System for automated dataset profiling, explainable EDA, and ML model building.',
    longDescription: 'An enterprise-grade Data Science Operating System pairing a Next.js 14 frontend with a Python FastAPI data & AI backend. Features automated dataset profiling, explainable exploratory data analysis, signal discovery scans with leakage detection, and automated ML model training reaching >97% accuracy.',
    image: '/images/AI.png',
    tech: ['Next.js', 'Python', 'FastAPI', 'Pandas', 'scikit-learn', 'Tailwind CSS'],
    github: 'https://github.com/varshan05446/AI-Data-Science',
    live: null,
    featured: true,
  },
  {
    id: 4,
    title: 'Inventory Management System',
    description: 'Offline-first Windows desktop application for managing raw materials, BOM recipes, production, stock, and payroll.',
    longDescription: 'An offline-first desktop application built with Electron, React 18, TypeScript, Tailwind CSS, and SQLite (sql.js). Features include dashboard analytics, purchase entry, production with BOM recipe consumption, finished-goods inventory, staff attendance, wages, overtime, dispatch, 20+ PDF/Excel reports, and automated encrypted backup/restore.',
    image: '/images/inventory.png',
    tech: ['Electron', 'React', 'TypeScript', 'Tailwind CSS', 'SQLite'],
    github: 'https://github.com/varshan054685/Inventory_Management',
    live: 'https://github.com/varshan054685/Inventory_Management/releases',
    featured: true,
  },
  {
    id: 5,
    title: 'Lumina Finance App',
    description: 'Modern finance tracking application with AI insights, budget goal setting, and comprehensive dashboard capabilities.',
    longDescription: 'Lumina is an advanced personal finance application designed to help users manage their money effectively. It features intuitive dashboards, transaction tracking, budget goal setting, and AI-driven predictive insights for smarter financial decisions.',
    image: '/images/lumina.png',
    tech: ['Next.js', 'TypeScript', 'Tailwind CSS', 'React', 'AI Insights'],
    github: 'https://github.com/varshan054685/studio.git',
    live: 'https://lumina-expense.netlify.app',
    featured: true,
  },
  {
    id: 6,
    title: 'Automatic Time-Table Scheduler',
    description: 'Automated scheduling engine designed to eliminate resource conflicts across multi-department academic timetables.',
    longDescription: 'Developed an automated scheduling engine designed to eliminate resource conflicts across multi-department academic timetables. Implemented responsive interactive schedule views using React.js backed by robust relational operations in PostgreSQL.',
    image: '/images/scheduler.png',
    tech: ['PostgreSQL', 'Express.js', 'React', 'Node.js', 'PERN Stack'],
    github: 'https://github.com/varshan054685/Automatic_Time-Table_scheduler',
    live: 'https://automatic-time-table-scheduler.vercel.app/',
    featured: true,
  },
  {
    id: 7,
    title: 'AI Conversational Assistant',
    description: 'Interactive AI chatbot delivering real-time user query resolutions built during a fast-paced hackathon.',
    longDescription: 'Collaborated in a fast-paced hackathon team to build an interactive AI chatbot delivering real-time user query resolutions. Awarded 1st place at the Internal Hackathon 2025. Connected a Python/Flask inference backend with an asynchronous JavaScript web front-end.',
    image: null,
    tech: ['Python', 'Flask', 'JavaScript', 'REST APIs', 'AI Chatbot'],
    github: 'https://github.com/varshan054685',
    live: null,
    featured: true,
  },
  {
    id: 8,
    title: 'Portfolio Website',
    description: 'Built and deployed a responsive personal portfolio showcasing projects, technical skills, and live web applications.',
    longDescription: 'Built and deployed a responsive personal portfolio showcasing projects, technical skills, and live web applications using Next.js, Tailwind CSS, and Framer Motion.',
    image: '/images/portfolio.png',
    tech: ['Next.js', 'Tailwind CSS', 'TypeScript', 'Framer Motion'],
    github: 'https://github.com/varshan054685/portfolio',
    live: 'https://varshan-portfolio.vercel.app',
    featured: true,
  },
];

export const experience = [
  {
    id: 1,
    type: 'award',
    title: '1st Prize – Internal Hackathon',
    organization: 'KPR College of Arts, Science and Research',
    year: '2025',
    description: 'Awarded 1st place for presenting an innovative chatbot-based solution.',
    icon: 'Trophy',
  },
  {
    id: 2,
    type: 'participation',
    title: 'Smart India Hackathon (SIH)',
    organization: 'National Level Innovation Challenge',
    year: 'Participant',
    description: 'Competed in a national innovation challenge; team solution design and prototyping.',
    icon: 'Globe',
  },
  {
    id: 3,
    type: 'participation',
    title: 'EVOLVE26 Singapore',
    organization: 'International Technology Summit',
    year: '2026',
    description: 'Participated in a technology-focused event featuring industry sessions, breakout tracks, and discussions on technology, leadership, and data impact.',
    icon: 'Handshake',
  },
  {
    id: 4,
    type: 'award',
    title: '2nd Prize – Football Tournament',
    organization: 'Literacy Mission Matriculation Hr. Sec. School',
    year: '2022',
    description: 'Awarded 2nd place in school football tournament.',
    icon: 'Medal',
  },
];

export const education = [
  {
    id: 1,
    degree: 'B.Com (Information Technology)',
    institution: 'KPR College of Arts, Science, and Research',
    location: 'Coimbatore',
    period: '2023 – 2026',
    description: 'Bachelor of Commerce in Information Technology · CGPA: 6.8 / 10.0',
    icon: 'GraduationCap',
  },
  {
    id: 2,
    degree: 'Higher Secondary Certificate (HSC)',
    institution: 'Literacy Mission Matriculation Hr. Sec. School',
    location: 'Coimbatore',
    period: '2021 – 2023',
    description: 'Completed Higher Secondary Education with 77% Aggregate',
    icon: 'School',
  },
];

