export const personalData = {
  name: 'Varshan K',
  title: 'B.Com (IT) Student | Front-End Developer',
  tagline: 'Building human-centered web experiences with passion and precision',
  description: 'Interactive and empathetic developer passionate about creating simple, human-centered designs and web solutions.',
  location: 'Coimbatore, Tamilnadu-641668',
  email: 'varshan4685@gmail.com',
  phone: '9626949995',
  linkedin: 'https://www.linkedin.com/in/varshan-k-v005',
  github: 'https://github.com/varshan054685',
  resumeLink: '/Varshan_Resume.pdf',
};

export const skills = {
  technical: [
    { name: 'HTML5', icon: 'Code2', level: 90, color: '#e34c26' },
    { name: 'CSS3', icon: 'Palette', level: 85, color: '#264de4' },
    { name: 'JavaScript', icon: 'FileJson', level: 80, color: '#f7df1e' },
    { name: 'React.js', icon: 'Atom', level: 78, color: '#61dafb' },
    { name: 'Node.js', icon: 'Server', level: 75, color: '#339933' },
    { name: 'MongoDB', icon: 'Database', level: 70, color: '#47a248' },
    { name: 'Express.js', icon: 'Globe', level: 72, color: '#ffffff' },
    { name: 'PostgreSQL', icon: 'Database', level: 65, color: '#336791' },
    { name: 'Tailwind CSS', icon: 'Wind', level: 88, color: '#06b6d4' },
    { name: 'Git & GitHub', icon: 'GitBranch', level: 80, color: '#f05032' },
  ],
  soft: [
    { name: 'Communication', icon: 'MessageCircle' },
    { name: 'Teamwork', icon: 'Users' },
    { name: 'Collaboration', icon: 'Handshake' },
    { name: 'Time Management', icon: 'Clock' },
    { name: 'Empathy', icon: 'Heart' },
    { name: 'Problem Solving', icon: 'Lightbulb' },
  ],
};

export const projects = [
  {
    id: 1,
    title: 'AI Chatbot',
    description: 'Team-based hackathon chatbot with real-time interaction. Won 1st prize at Internal Hackathon 2025 for this innovative solution.',
    longDescription: 'An intelligent chatbot built for a hackathon competition that enables real-time conversations. The project features natural language processing capabilities, responsive UI, and seamless integration with backend services. This project won the 1st prize at the Internal Hackathon 2025.',
    image: '/images/chatbot.jpg',
    tech: ['HTML', 'CSS', 'JavaScript', 'Python'],
    github: null,
    live: null,
    featured: true,
  },
  {
    id: 2,
    title: 'E-Commerce Website',
    description: 'Full-stack online shopping platform with authentication, cart functionality, and payment integration.',
    longDescription: 'A complete e-commerce solution built with the MERN stack. Features include user authentication, product catalog, shopping cart, checkout process, and admin dashboard. The application is fully responsive and optimized for performance.',
    image: '/images/ecommerce.jpg',
    tech: ['MongoDB', 'Express.js', 'React', 'Node.js'],
    github: null,
    live: null,
    featured: true,
  },
  {
    id: 3,
    title: 'Event Registration System',
    description: 'Web app for college event management and student registration with real-time updates.',
    longDescription: 'A comprehensive event management platform designed for educational institutions. Features include event creation, student registration, automated email notifications, attendance tracking, and analytics dashboard.',
    image: '/images/event.jpg',
    tech: ['MongoDB', 'Express.js', 'React', 'Node.js'],
    github: 'https://github.com/varshan054685/college-event-registration',
    live: 'https://college-event-registration-ten.vercel.app/',
    featured: true,
  },
  {
    id: 4,
    title: 'Automatic Time-Table Scheduler',
    description: 'Automated scheduling system to reduce timetable conflicts using AI algorithms.',
    longDescription: 'An intelligent scheduling system that automatically generates optimized timetables for educational institutions. Uses constraint satisfaction algorithms to minimize conflicts and maximize resource utilization.',
    image: '/images/scheduler.jpg',
    tech: ['PostgreSQL', 'Express.js', 'React', 'Node.js'],
    github: 'https://github.com/varshan054685/Automatic_Time-Table_scheduler',
    live: 'https://automatic-time-table-scheduler.vercel.app/',
    featured: true,
  },
];

export const experience = [
  {
    id: 1,
    type: 'award',
    title: '1st Prize - Internal Hackathon',
    organization: 'KPR College',
    year: '2025',
    description: 'Won first place for presenting an innovative tech solution: AI Chatbot project',
    icon: 'Trophy',
  },
  {
    id: 2,
    type: 'award',
    title: '2nd Prize - Football Tournament',
    organization: 'Literacy Mission MHSS',
    year: '2022',
    description: 'Journal Level Football Tournament',
    icon: 'Medal',
  },
  {
    id: 3,
    type: 'participation',
    title: 'Tamizhi Hackathon',
    organization: 'State Level Event',
    year: '2025',
    description: 'Chosen to participate in a state-level innovation event dedicated to advancing Tamil language technology solutions',
    icon: 'Handshake',
  },
  {
    id: 4,
    type: 'participation',
    title: 'Smart India Hackathon (SIH)',
    organization: 'National Level',
    year: '2024',
    description: 'Competed in a national-level innovation challenge, contributing to team-based solution design, development, and presentation',
    icon: 'Globe',
  },
];

export const education = [
  {
    id: 1,
    degree: 'B.Com (Information Technology)',
    institution: 'KPR College of Arts, Science & Research',
    location: 'Coimbatore',
    period: '2023 – 2026',
    description: 'Pursuing Bachelor of Commerce with specialization in Information Technology',
    icon: 'GraduationCap',
  },
  {
    id: 2,
    degree: 'Higher Secondary Education (HSC)',
    institution: 'Literacy Mission Matriculation HSS',
    location: 'Coimbatore',
    period: '2021 – 2023',
    description: 'Completed with 77% aggregate',
    icon: 'School',
  },
];
